### ISSUE TITLE
Can't add new users via UmbBackofficeMembershipProvider in 7.4.1?

### ISSUE THREAD

**Issue by schrepel** [Bitmapped/UmbBackofficeMembershipProvider#1]
Up thru Umbraco 7.1 or so, we'd used the built-in BackOffice membership stuff so that Active Directory users could log in, worked great.

Now on 7.4.1, we've added the UmbBackOfficeMembershipProvider via NuGet, which is working great for users that have already logged in before.

But whereas new users used to be able to login (then I'd increase their permissions in Umbraco), now that doesn't seem to be working. Wondering if there's a different way for new users to connect, or whether maybe something else is going on. Should I be having to create their user in Umbraco first?

In your experience, should new ActiveDirectory users just be able to login the same as they had before (whether the user already existed in Umbraco or not?)

**Comment by Bitmapped** [comment]
In Umbraco 7.3+, you have to create the user accounts in Umbraco first before the user can login via Active Directory. Users aren't automatically created like they were with older versions.
