### ISSUE TITLE
User changes in Umb 7.7 beta might break this?

### ISSUE THREAD

**Issue by brianpatton** [Bitmapped/UmbBackofficeMembershipProvider#2]
Playing with the beta of Umbraco 7.7 and with all the user changes, I'm having some issues with this now.  Looks like they require the username to be in an email format which doesn't match up w/ the way our Active Directory works.  Any ideas?  Thanks!

**Comment by brianpatton** [comment]
Additional info ... here is the error I'm getting after enabling the owin:appStartup changes:

Method not found: 'Umbraco.Core.Security.BackOfficeUserManager Umbraco.Core.Security.BackOfficeUserManager.Create(Microsoft.AspNet.Identity.Owin.IdentityFactoryOptions`1<Umbraco.Core.Security.BackOfficeUserManager>, Umbraco.Core.Services.IUserService, Umbraco.Core.Services.IExternalLoginService, Umbraco.Core.Security.MembershipProviderBase)'.

**Comment by Bitmapped** [comment]
I haven't had time to play with the 7.7 beta yet. The underlying code of the BackOfficeUserManager class in Umbraco.Core hasn't changed for a year, so I'm not sure what broke there. Do you have a stack trace further up to see what is calling it?

**Comment by brianpatton** [comment]
Yes, here you go:

`[MissingMethodException: Method not found: 'Umbraco.Core.Security.BackOfficeUserManager Umbraco.Core.Security.BackOfficeUserManager.Create(Microsoft.AspNet.Identity.Owin.IdentityFactoryOptions`1<Umbraco.Core.Security.BackOfficeUserManager>, Umbraco.Core.Services.IUserService, Umbraco.Core.Services.IExternalLoginService, Umbraco.Core.Security.MembershipProviderBase)'.]
   UmbBackofficeMembershipProvider.<>c__DisplayClass0_0.<Configuration>b__0(IdentityFactoryOptions`1 options, IOwinContext context) +0
   Microsoft.AspNet.Identity.Owin.IdentityFactoryProvider`1.Create(IdentityFactoryOptions`1 options, IOwinContext context) +14
   Microsoft.AspNet.Identity.Owin.<Invoke>d__0.MoveNext() +104
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +182
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +180
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155`

**Comment by Bitmapped** [comment]
OK, things aren't immediately obvious here. I'll have to look with a debugger at some point.

So that I can better understand the situation, did you upgrade an existing working Umbraco install that had UmbBackofficeMembershipProvider or was this a new setup?

**Comment by brianpatton** [comment]
I just did a quick clean install of 7.7beta using visual studio to test out a few features.  The new users features are really nice, so wanted to test alongside this as we rely on it for authentication.  Let me know what you find, thanks!

**Comment by Bitmapped** [comment]
I was able to replicate the error with Umbraco 7.7 with an upgraded install from a working 7.6.5 install.

There was a breaking change introduced in this commit https://github.com/umbraco/Umbraco-CMS/commit/97471f667d8e8ee574a520a5c9f7248bacf29536 . I'm trying to determine how to work around it.

**Comment by Bitmapped** [comment]
I've updated the codebase with changes that fix the Umbraco 7.7.0 compatibility issue. I could not find a way to make things backwards-compatible. UmbBackOfficeMembershipProvider 3.0.0 only works with Umbraco 7.4.2-7.6.x, and the new code in UmbBackOfficeMembershipProvider 4.0.0 is only compatible with Umbraco 7.7.0+.

**Comment by Bitmapped** [comment]
I've pushed the updated code to NuGet at https://www.nuget.org/packages/UmbBackofficeMembershipProvider/4.0.0-beta.

**Comment by Bitmapped** [comment]
As a note, a shim was added to the final release of Umbraco 7.7.0 to work around the breaking changes in the beta. You can continue using UmbBackofficeMembershipProvider 3.0.0 with 7.7.0+.

I've also released UmbBackofficeMembershipProvider 4.1.1, which requires Umbraco 7.7.2+. This version takes advantage of API changes to allow for the automatic creation of backoffice users for logins authenticated by your membership provider.
