### ISSUE TITLE
How to fallback to Umbraco Login if user is not in AD?

### ISSUE THREAD

**Issue by biapar** [Bitmapped/UmbBackofficeMembershipProvider#8]
Is't possible to fallback to Umbraco Login if the user is not in Active Directory?

**Comment by Bitmapped** [comment]
Not as currently implemented. It might be possible to build hooks in that would call Umbraco's default provider if AD authentication failed but that's not something I personally have plans to add. If you would like to do that and submit a pull request, I'd be open to including it in the codebase.
